import { useRouter } from "next/router";
import Head from "next/head";
import { useEffect, useState } from "react";
import logo from "../../public/images/logo.png";
import Image from "next/image";
import Footer from "../../components/Footer";
import axios from "axios";
import { toast } from "react-toastify";
import { Formik, Field, Form } from "formik";

export default function ResetPassword() {
  const [error, setError] = useState("");
  const [success, setSuccess] = useState("");
  const router = useRouter();
  
  const { tokenid } = router.query;

  // initial form value
  const initialValues = {
    user: {
      password: "",
    },
    confirmPassword: "",
  };

  const onSubmit = async (values, onSubmitProps) => {
    if (values.user.password !== values.confirmPassword) {
      onSubmitProps.resetForm();
      setTimeout(() => {
        setError("");
      }, 5000);
      return setError("Passwords Don't Match");
    }
    try {
      const { data } = await axios.post(
        `/api/auth/reset-password/${resetToken}`,
        values
      );

      setSuccess(data.message);
      onSubmitProps.resetForm();
      toast.success(`Password Reset Success`, {
        position: "top-center",
        theme: "colored",
        autoClose: 2000,
      });
    } catch (error) {
      setError(error.response.data.error);
      onSubmitProps.resetForm();
      setTimeout(() => {
        setError("");
      }, 5000);
    }
  };

  useEffect(() => {
    const redirectPage = async () => {
      if (success) {
        router.push("/");
      }
    };
    redirectPage();
  }, [success, router]);

  return (
    <>
      <Head>
        <title>Reset-Password</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="flex flex-col h-screen justify-between">
        <div className="flex justify-start p-4">
          <Image
            alt="profile pic"
            src={logo}
            className=""
            width={90}
            height={62}
            placeholder="blur"
            blurDataURL
          />
        </div>
        <div className="flex flex-col items-center">
          <div className="w-80 space-y-8">
            <div className="flex flex-col items-center">
              <h2 className="text-3xl font-extrabold text-gray-900">
                Reset Password
              </h2>
              <span className="text-sm font-normal">
                Enter you new password below.
              </span>
            </div>

            <Formik
              initialValues={initialValues}
              onSubmit={onSubmit}
              className="space-y-2"
            >
              <Form>
                <div className="rounded-md shadow-sm space-y-2">
                  <div>
                    <Field
                      className="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-b-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm"
                      type="password"
                      aria-label="password"
                      placeholder="Enter new password"
                      name="user.password"
                    />
                  </div>
                  <div>
                    <Field
                      className="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-b-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm"
                      type="password"
                      aria-label="confirmPassword"
                      placeholder="Confirm new password"
                      name="confirmPassword"
                    />
                  </div>
                </div>
                <div className="flex flex-col">
                  <button
                    type="submit"
                    className="rounded-lg bg-[#4092CF] text-base px-3 py-2 hover:bg-blue-400 transition duration-300"
                  >
                    Reset Password
                  </button>
                  {error && <span className="text-red-500">{error}</span>}
                </div>
              </Form>
            </Formik>
          </div>
        </div>
        <Footer />
      </div>
    </>
  );
}
